#VARIABLES

INSTALL		= install
PROGRAMS 	= yumpkgs
VERSION		= HEAD

#TARGETS

.PHONY: all help proghelp release

#all: generate the programs and some other targets
all: $(PROGRAMS) proghelp

#help: display this message
help:
	@echo -e "Some useful targets are:\n"
	@grep -E '^#[^:]+:' Makefile|tr -d '#'
	@echo ''

#proghelp: generate the programs help file
proghelp:
	for p in $(PROGRAMS);do \
		egrep -o '#\*.+' $$p|sed 's/#\*//g' > $$p.help;  \
	done

#run: run every compiled program
run: $(PROGRAMS)
	for p in $(PROGRAMS);do \
		echo Program: $$p;\
		./$$p; \
	done

#release VERSION=<version>(ex.: v0.04): make a release
release:
	git archive --format=zip -o releases/yumpkgs-$(VERSION).zip $(VERSION)
	echo "<p>This is automatically generated whenever a new release is build.</p>Log:<pre class=\"cli\">" > blogger-post.html
	git log >> blogger-post.html
	echo '</pre>' >> blogger-post.html
	google blogger post -n "yumpkgs-$(VERSION)" -t "yumpkgs,FOSS,Windows,English" blogger-post.html

#install: install the programs
install:
	for p in $(PROGRAMS);do \
		$(INSTALL) $$p /usr/bin/; \
	done

#clean: clean files generated by this makefile
clean:
	rm -f *~
